switching:
  architecture-pool:
    - OX
    - OXII
    - XOV
    - XOV++
    - XOV#
    - SXOV
general:
  verbosity: v
  logfile: true
  learning: true
  default-architecture: OX
  endorsement-policy: 1