// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: gbft.proto
// Protobuf Java Version: 4.28.2

package com.gbft.framework.data;

public interface OperationSetOrBuilder extends
    // @@protoc_insertion_point(interface_extends:OperationSet)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 record = 1;</code>
   * @return The record.
   */
  int getRecord();

  /**
   * <code>.Operation op = 2;</code>
   * @return The enum numeric value on the wire for op.
   */
  int getOpValue();
  /**
   * <code>.Operation op = 2;</code>
   * @return The op.
   */
  com.gbft.framework.data.Operation getOp();

  /**
   * <code>int32 value = 3;</code>
   * @return The value.
   */
  int getValue();
}
