// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: gbft.proto
// Protobuf Java Version: 4.28.2

package com.gbft.framework.data;

/**
 * Protobuf type {@code RequestDataList}
 */
public final class RequestDataList extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:RequestDataList)
    RequestDataListOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 28,
      /* patch= */ 2,
      /* suffix= */ "",
      RequestDataList.class.getName());
  }
  // Use RequestDataList.newBuilder() to construct.
  private RequestDataList(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private RequestDataList() {
    reqDataList_ = java.util.Collections.emptyList();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.gbft.framework.data.Gbft.internal_static_RequestDataList_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.gbft.framework.data.Gbft.internal_static_RequestDataList_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.gbft.framework.data.RequestDataList.class, com.gbft.framework.data.RequestDataList.Builder.class);
  }

  public static final int REQDATALIST_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private java.util.List<com.gbft.framework.data.RequestData> reqDataList_;
  /**
   * <code>repeated .RequestData reqDataList = 1;</code>
   */
  @java.lang.Override
  public java.util.List<com.gbft.framework.data.RequestData> getReqDataListList() {
    return reqDataList_;
  }
  /**
   * <code>repeated .RequestData reqDataList = 1;</code>
   */
  @java.lang.Override
  public java.util.List<? extends com.gbft.framework.data.RequestDataOrBuilder> 
      getReqDataListOrBuilderList() {
    return reqDataList_;
  }
  /**
   * <code>repeated .RequestData reqDataList = 1;</code>
   */
  @java.lang.Override
  public int getReqDataListCount() {
    return reqDataList_.size();
  }
  /**
   * <code>repeated .RequestData reqDataList = 1;</code>
   */
  @java.lang.Override
  public com.gbft.framework.data.RequestData getReqDataList(int index) {
    return reqDataList_.get(index);
  }
  /**
   * <code>repeated .RequestData reqDataList = 1;</code>
   */
  @java.lang.Override
  public com.gbft.framework.data.RequestDataOrBuilder getReqDataListOrBuilder(
      int index) {
    return reqDataList_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < reqDataList_.size(); i++) {
      output.writeMessage(1, reqDataList_.get(i));
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    for (int i = 0; i < reqDataList_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, reqDataList_.get(i));
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.gbft.framework.data.RequestDataList)) {
      return super.equals(obj);
    }
    com.gbft.framework.data.RequestDataList other = (com.gbft.framework.data.RequestDataList) obj;

    if (!getReqDataListList()
        .equals(other.getReqDataListList())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getReqDataListCount() > 0) {
      hash = (37 * hash) + REQDATALIST_FIELD_NUMBER;
      hash = (53 * hash) + getReqDataListList().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.gbft.framework.data.RequestDataList parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.gbft.framework.data.RequestDataList parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.gbft.framework.data.RequestDataList parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.gbft.framework.data.RequestDataList parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.gbft.framework.data.RequestDataList parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.gbft.framework.data.RequestDataList parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.gbft.framework.data.RequestDataList parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.gbft.framework.data.RequestDataList parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.gbft.framework.data.RequestDataList parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.gbft.framework.data.RequestDataList parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.gbft.framework.data.RequestDataList parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.gbft.framework.data.RequestDataList parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.gbft.framework.data.RequestDataList prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code RequestDataList}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:RequestDataList)
      com.gbft.framework.data.RequestDataListOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.gbft.framework.data.Gbft.internal_static_RequestDataList_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.gbft.framework.data.Gbft.internal_static_RequestDataList_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.gbft.framework.data.RequestDataList.class, com.gbft.framework.data.RequestDataList.Builder.class);
    }

    // Construct using com.gbft.framework.data.RequestDataList.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      if (reqDataListBuilder_ == null) {
        reqDataList_ = java.util.Collections.emptyList();
      } else {
        reqDataList_ = null;
        reqDataListBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000001);
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.gbft.framework.data.Gbft.internal_static_RequestDataList_descriptor;
    }

    @java.lang.Override
    public com.gbft.framework.data.RequestDataList getDefaultInstanceForType() {
      return com.gbft.framework.data.RequestDataList.getDefaultInstance();
    }

    @java.lang.Override
    public com.gbft.framework.data.RequestDataList build() {
      com.gbft.framework.data.RequestDataList result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.gbft.framework.data.RequestDataList buildPartial() {
      com.gbft.framework.data.RequestDataList result = new com.gbft.framework.data.RequestDataList(this);
      buildPartialRepeatedFields(result);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartialRepeatedFields(com.gbft.framework.data.RequestDataList result) {
      if (reqDataListBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0)) {
          reqDataList_ = java.util.Collections.unmodifiableList(reqDataList_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.reqDataList_ = reqDataList_;
      } else {
        result.reqDataList_ = reqDataListBuilder_.build();
      }
    }

    private void buildPartial0(com.gbft.framework.data.RequestDataList result) {
      int from_bitField0_ = bitField0_;
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.gbft.framework.data.RequestDataList) {
        return mergeFrom((com.gbft.framework.data.RequestDataList)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.gbft.framework.data.RequestDataList other) {
      if (other == com.gbft.framework.data.RequestDataList.getDefaultInstance()) return this;
      if (reqDataListBuilder_ == null) {
        if (!other.reqDataList_.isEmpty()) {
          if (reqDataList_.isEmpty()) {
            reqDataList_ = other.reqDataList_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureReqDataListIsMutable();
            reqDataList_.addAll(other.reqDataList_);
          }
          onChanged();
        }
      } else {
        if (!other.reqDataList_.isEmpty()) {
          if (reqDataListBuilder_.isEmpty()) {
            reqDataListBuilder_.dispose();
            reqDataListBuilder_ = null;
            reqDataList_ = other.reqDataList_;
            bitField0_ = (bitField0_ & ~0x00000001);
            reqDataListBuilder_ = 
              com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                 getReqDataListFieldBuilder() : null;
          } else {
            reqDataListBuilder_.addAllMessages(other.reqDataList_);
          }
        }
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              com.gbft.framework.data.RequestData m =
                  input.readMessage(
                      com.gbft.framework.data.RequestData.parser(),
                      extensionRegistry);
              if (reqDataListBuilder_ == null) {
                ensureReqDataListIsMutable();
                reqDataList_.add(m);
              } else {
                reqDataListBuilder_.addMessage(m);
              }
              break;
            } // case 10
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.util.List<com.gbft.framework.data.RequestData> reqDataList_ =
      java.util.Collections.emptyList();
    private void ensureReqDataListIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        reqDataList_ = new java.util.ArrayList<com.gbft.framework.data.RequestData>(reqDataList_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilder<
        com.gbft.framework.data.RequestData, com.gbft.framework.data.RequestData.Builder, com.gbft.framework.data.RequestDataOrBuilder> reqDataListBuilder_;

    /**
     * <code>repeated .RequestData reqDataList = 1;</code>
     */
    public java.util.List<com.gbft.framework.data.RequestData> getReqDataListList() {
      if (reqDataListBuilder_ == null) {
        return java.util.Collections.unmodifiableList(reqDataList_);
      } else {
        return reqDataListBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .RequestData reqDataList = 1;</code>
     */
    public int getReqDataListCount() {
      if (reqDataListBuilder_ == null) {
        return reqDataList_.size();
      } else {
        return reqDataListBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .RequestData reqDataList = 1;</code>
     */
    public com.gbft.framework.data.RequestData getReqDataList(int index) {
      if (reqDataListBuilder_ == null) {
        return reqDataList_.get(index);
      } else {
        return reqDataListBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .RequestData reqDataList = 1;</code>
     */
    public Builder setReqDataList(
        int index, com.gbft.framework.data.RequestData value) {
      if (reqDataListBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureReqDataListIsMutable();
        reqDataList_.set(index, value);
        onChanged();
      } else {
        reqDataListBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .RequestData reqDataList = 1;</code>
     */
    public Builder setReqDataList(
        int index, com.gbft.framework.data.RequestData.Builder builderForValue) {
      if (reqDataListBuilder_ == null) {
        ensureReqDataListIsMutable();
        reqDataList_.set(index, builderForValue.build());
        onChanged();
      } else {
        reqDataListBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .RequestData reqDataList = 1;</code>
     */
    public Builder addReqDataList(com.gbft.framework.data.RequestData value) {
      if (reqDataListBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureReqDataListIsMutable();
        reqDataList_.add(value);
        onChanged();
      } else {
        reqDataListBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .RequestData reqDataList = 1;</code>
     */
    public Builder addReqDataList(
        int index, com.gbft.framework.data.RequestData value) {
      if (reqDataListBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureReqDataListIsMutable();
        reqDataList_.add(index, value);
        onChanged();
      } else {
        reqDataListBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .RequestData reqDataList = 1;</code>
     */
    public Builder addReqDataList(
        com.gbft.framework.data.RequestData.Builder builderForValue) {
      if (reqDataListBuilder_ == null) {
        ensureReqDataListIsMutable();
        reqDataList_.add(builderForValue.build());
        onChanged();
      } else {
        reqDataListBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .RequestData reqDataList = 1;</code>
     */
    public Builder addReqDataList(
        int index, com.gbft.framework.data.RequestData.Builder builderForValue) {
      if (reqDataListBuilder_ == null) {
        ensureReqDataListIsMutable();
        reqDataList_.add(index, builderForValue.build());
        onChanged();
      } else {
        reqDataListBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .RequestData reqDataList = 1;</code>
     */
    public Builder addAllReqDataList(
        java.lang.Iterable<? extends com.gbft.framework.data.RequestData> values) {
      if (reqDataListBuilder_ == null) {
        ensureReqDataListIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, reqDataList_);
        onChanged();
      } else {
        reqDataListBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .RequestData reqDataList = 1;</code>
     */
    public Builder clearReqDataList() {
      if (reqDataListBuilder_ == null) {
        reqDataList_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        reqDataListBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .RequestData reqDataList = 1;</code>
     */
    public Builder removeReqDataList(int index) {
      if (reqDataListBuilder_ == null) {
        ensureReqDataListIsMutable();
        reqDataList_.remove(index);
        onChanged();
      } else {
        reqDataListBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .RequestData reqDataList = 1;</code>
     */
    public com.gbft.framework.data.RequestData.Builder getReqDataListBuilder(
        int index) {
      return getReqDataListFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .RequestData reqDataList = 1;</code>
     */
    public com.gbft.framework.data.RequestDataOrBuilder getReqDataListOrBuilder(
        int index) {
      if (reqDataListBuilder_ == null) {
        return reqDataList_.get(index);  } else {
        return reqDataListBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .RequestData reqDataList = 1;</code>
     */
    public java.util.List<? extends com.gbft.framework.data.RequestDataOrBuilder> 
         getReqDataListOrBuilderList() {
      if (reqDataListBuilder_ != null) {
        return reqDataListBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(reqDataList_);
      }
    }
    /**
     * <code>repeated .RequestData reqDataList = 1;</code>
     */
    public com.gbft.framework.data.RequestData.Builder addReqDataListBuilder() {
      return getReqDataListFieldBuilder().addBuilder(
          com.gbft.framework.data.RequestData.getDefaultInstance());
    }
    /**
     * <code>repeated .RequestData reqDataList = 1;</code>
     */
    public com.gbft.framework.data.RequestData.Builder addReqDataListBuilder(
        int index) {
      return getReqDataListFieldBuilder().addBuilder(
          index, com.gbft.framework.data.RequestData.getDefaultInstance());
    }
    /**
     * <code>repeated .RequestData reqDataList = 1;</code>
     */
    public java.util.List<com.gbft.framework.data.RequestData.Builder> 
         getReqDataListBuilderList() {
      return getReqDataListFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilder<
        com.gbft.framework.data.RequestData, com.gbft.framework.data.RequestData.Builder, com.gbft.framework.data.RequestDataOrBuilder> 
        getReqDataListFieldBuilder() {
      if (reqDataListBuilder_ == null) {
        reqDataListBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
            com.gbft.framework.data.RequestData, com.gbft.framework.data.RequestData.Builder, com.gbft.framework.data.RequestDataOrBuilder>(
                reqDataList_,
                ((bitField0_ & 0x00000001) != 0),
                getParentForChildren(),
                isClean());
        reqDataList_ = null;
      }
      return reqDataListBuilder_;
    }

    // @@protoc_insertion_point(builder_scope:RequestDataList)
  }

  // @@protoc_insertion_point(class_scope:RequestDataList)
  private static final com.gbft.framework.data.RequestDataList DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.gbft.framework.data.RequestDataList();
  }

  public static com.gbft.framework.data.RequestDataList getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<RequestDataList>
      PARSER = new com.google.protobuf.AbstractParser<RequestDataList>() {
    @java.lang.Override
    public RequestDataList parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<RequestDataList> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<RequestDataList> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.gbft.framework.data.RequestDataList getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

