// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: gbft.proto

package com.gbft.framework.data;

public interface RequestDataListOrBuilder extends
    // @@protoc_insertion_point(interface_extends:RequestDataList)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .RequestData reqDataList = 1;</code>
   */
  java.util.List<com.gbft.framework.data.RequestData> 
      getReqDataListList();
  /**
   * <code>repeated .RequestData reqDataList = 1;</code>
   */
  com.gbft.framework.data.RequestData getReqDataList(int index);
  /**
   * <code>repeated .RequestData reqDataList = 1;</code>
   */
  int getReqDataListCount();
  /**
   * <code>repeated .RequestData reqDataList = 1;</code>
   */
  java.util.List<? extends com.gbft.framework.data.RequestDataOrBuilder> 
      getReqDataListOrBuilderList();
  /**
   * <code>repeated .RequestData reqDataList = 1;</code>
   */
  com.gbft.framework.data.RequestDataOrBuilder getReqDataListOrBuilder(
      int index);
}
