// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: gbft.proto
// Protobuf Java Version: 4.28.2

package com.gbft.framework.data;

/**
 * Protobuf type {@code RequestData}
 */
public final class RequestData extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:RequestData)
    RequestDataOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 28,
      /* patch= */ 2,
      /* suffix= */ "",
      RequestData.class.getName());
  }
  // Use RequestData.newBuilder() to construct.
  private RequestData(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private RequestData() {
    readSet_ = java.util.Collections.emptyList();
    writeSet_ = java.util.Collections.emptyList();
    reportQuorum_ = java.util.Collections.emptyList();
    requestDummy_ = com.google.protobuf.ByteString.EMPTY;
    reqLists_ = java.util.Collections.emptyList();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.gbft.framework.data.Gbft.internal_static_RequestData_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.gbft.framework.data.Gbft.internal_static_RequestData_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.gbft.framework.data.RequestData.class, com.gbft.framework.data.RequestData.Builder.class);
  }

  private int bitField0_;
  public static final int CLIENT_FIELD_NUMBER = 1;
  private int client_ = 0;
  /**
   * <code>int32 client = 1;</code>
   * @return The client.
   */
  @java.lang.Override
  public int getClient() {
    return client_;
  }

  public static final int REQUEST_NUM_FIELD_NUMBER = 2;
  private long requestNum_ = 0L;
  /**
   * <code>int64 request_num = 2;</code>
   * @return The requestNum.
   */
  @java.lang.Override
  public long getRequestNum() {
    return requestNum_;
  }

  public static final int VALUE_FIELD_NUMBER = 5;
  private int value_ = 0;
  /**
   * <pre>
   * int32 record = 3;
   * Operation operation = 4;
   * </pre>
   *
   * <code>int32 value = 5;</code>
   * @return The value.
   */
  @java.lang.Override
  public int getValue() {
    return value_;
  }

  public static final int READ_SET_FIELD_NUMBER = 15;
  @SuppressWarnings("serial")
  private java.util.List<com.gbft.framework.data.OperationSet> readSet_;
  /**
   * <code>repeated .OperationSet read_set = 15;</code>
   */
  @java.lang.Override
  public java.util.List<com.gbft.framework.data.OperationSet> getReadSetList() {
    return readSet_;
  }
  /**
   * <code>repeated .OperationSet read_set = 15;</code>
   */
  @java.lang.Override
  public java.util.List<? extends com.gbft.framework.data.OperationSetOrBuilder> 
      getReadSetOrBuilderList() {
    return readSet_;
  }
  /**
   * <code>repeated .OperationSet read_set = 15;</code>
   */
  @java.lang.Override
  public int getReadSetCount() {
    return readSet_.size();
  }
  /**
   * <code>repeated .OperationSet read_set = 15;</code>
   */
  @java.lang.Override
  public com.gbft.framework.data.OperationSet getReadSet(int index) {
    return readSet_.get(index);
  }
  /**
   * <code>repeated .OperationSet read_set = 15;</code>
   */
  @java.lang.Override
  public com.gbft.framework.data.OperationSetOrBuilder getReadSetOrBuilder(
      int index) {
    return readSet_.get(index);
  }

  public static final int WRITE_SET_FIELD_NUMBER = 16;
  @SuppressWarnings("serial")
  private java.util.List<com.gbft.framework.data.OperationSet> writeSet_;
  /**
   * <code>repeated .OperationSet write_set = 16;</code>
   */
  @java.lang.Override
  public java.util.List<com.gbft.framework.data.OperationSet> getWriteSetList() {
    return writeSet_;
  }
  /**
   * <code>repeated .OperationSet write_set = 16;</code>
   */
  @java.lang.Override
  public java.util.List<? extends com.gbft.framework.data.OperationSetOrBuilder> 
      getWriteSetOrBuilderList() {
    return writeSet_;
  }
  /**
   * <code>repeated .OperationSet write_set = 16;</code>
   */
  @java.lang.Override
  public int getWriteSetCount() {
    return writeSet_.size();
  }
  /**
   * <code>repeated .OperationSet write_set = 16;</code>
   */
  @java.lang.Override
  public com.gbft.framework.data.OperationSet getWriteSet(int index) {
    return writeSet_.get(index);
  }
  /**
   * <code>repeated .OperationSet write_set = 16;</code>
   */
  @java.lang.Override
  public com.gbft.framework.data.OperationSetOrBuilder getWriteSetOrBuilder(
      int index) {
    return writeSet_.get(index);
  }

  public static final int TIMESTAMP_FIELD_NUMBER = 6;
  private com.google.protobuf.Timestamp timestamp_;
  /**
   * <code>.google.protobuf.Timestamp timestamp = 6;</code>
   * @return Whether the timestamp field is set.
   */
  @java.lang.Override
  public boolean hasTimestamp() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <code>.google.protobuf.Timestamp timestamp = 6;</code>
   * @return The timestamp.
   */
  @java.lang.Override
  public com.google.protobuf.Timestamp getTimestamp() {
    return timestamp_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : timestamp_;
  }
  /**
   * <code>.google.protobuf.Timestamp timestamp = 6;</code>
   */
  @java.lang.Override
  public com.google.protobuf.TimestampOrBuilder getTimestampOrBuilder() {
    return timestamp_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : timestamp_;
  }

  public static final int REPORT_QUORUM_FIELD_NUMBER = 7;
  @SuppressWarnings("serial")
  private java.util.List<com.gbft.framework.data.LearningData> reportQuorum_;
  /**
   * <code>repeated .LearningData report_quorum = 7;</code>
   */
  @java.lang.Override
  public java.util.List<com.gbft.framework.data.LearningData> getReportQuorumList() {
    return reportQuorum_;
  }
  /**
   * <code>repeated .LearningData report_quorum = 7;</code>
   */
  @java.lang.Override
  public java.util.List<? extends com.gbft.framework.data.LearningDataOrBuilder> 
      getReportQuorumOrBuilderList() {
    return reportQuorum_;
  }
  /**
   * <code>repeated .LearningData report_quorum = 7;</code>
   */
  @java.lang.Override
  public int getReportQuorumCount() {
    return reportQuorum_.size();
  }
  /**
   * <code>repeated .LearningData report_quorum = 7;</code>
   */
  @java.lang.Override
  public com.gbft.framework.data.LearningData getReportQuorum(int index) {
    return reportQuorum_.get(index);
  }
  /**
   * <code>repeated .LearningData report_quorum = 7;</code>
   */
  @java.lang.Override
  public com.gbft.framework.data.LearningDataOrBuilder getReportQuorumOrBuilder(
      int index) {
    return reportQuorum_.get(index);
  }

  public static final int REQUEST_DUMMY_FIELD_NUMBER = 8;
  private com.google.protobuf.ByteString requestDummy_ = com.google.protobuf.ByteString.EMPTY;
  /**
   * <code>bytes request_dummy = 8;</code>
   * @return The requestDummy.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString getRequestDummy() {
    return requestDummy_;
  }

  public static final int COMPUTE_FACTOR_FIELD_NUMBER = 9;
  private int computeFactor_ = 0;
  /**
   * <code>int32 compute_factor = 9;</code>
   * @return The computeFactor.
   */
  @java.lang.Override
  public int getComputeFactor() {
    return computeFactor_;
  }

  public static final int REPLY_SIZE_FIELD_NUMBER = 10;
  private int replySize_ = 0;
  /**
   * <code>int32 reply_size = 10;</code>
   * @return The replySize.
   */
  @java.lang.Override
  public int getReplySize() {
    return replySize_;
  }

  public static final int EARLY_EXEC_RESULT_FIELD_NUMBER = 11;
  private int earlyExecResult_ = 0;
  /**
   * <code>int32 early_exec_result = 11;</code>
   * @return The earlyExecResult.
   */
  @java.lang.Override
  public int getEarlyExecResult() {
    return earlyExecResult_;
  }

  public static final int IS_TNX_VALID_FIELD_NUMBER = 12;
  private boolean isTnxValid_ = false;
  /**
   * <code>bool is_tnx_valid = 12;</code>
   * @return The isTnxValid.
   */
  @java.lang.Override
  public boolean getIsTnxValid() {
    return isTnxValid_;
  }

  public static final int CURRENT_VERSION_FIELD_NUMBER = 13;
  private long currentVersion_ = 0L;
  /**
   * <code>int64 current_version = 13;</code>
   * @return The currentVersion.
   */
  @java.lang.Override
  public long getCurrentVersion() {
    return currentVersion_;
  }

  public static final int REQLISTS_FIELD_NUMBER = 14;
  @SuppressWarnings("serial")
  private java.util.List<com.gbft.framework.data.RequestDataList> reqLists_;
  /**
   * <code>repeated .RequestDataList reqLists = 14;</code>
   */
  @java.lang.Override
  public java.util.List<com.gbft.framework.data.RequestDataList> getReqListsList() {
    return reqLists_;
  }
  /**
   * <code>repeated .RequestDataList reqLists = 14;</code>
   */
  @java.lang.Override
  public java.util.List<? extends com.gbft.framework.data.RequestDataListOrBuilder> 
      getReqListsOrBuilderList() {
    return reqLists_;
  }
  /**
   * <code>repeated .RequestDataList reqLists = 14;</code>
   */
  @java.lang.Override
  public int getReqListsCount() {
    return reqLists_.size();
  }
  /**
   * <code>repeated .RequestDataList reqLists = 14;</code>
   */
  @java.lang.Override
  public com.gbft.framework.data.RequestDataList getReqLists(int index) {
    return reqLists_.get(index);
  }
  /**
   * <code>repeated .RequestDataList reqLists = 14;</code>
   */
  @java.lang.Override
  public com.gbft.framework.data.RequestDataListOrBuilder getReqListsOrBuilder(
      int index) {
    return reqLists_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (client_ != 0) {
      output.writeInt32(1, client_);
    }
    if (requestNum_ != 0L) {
      output.writeInt64(2, requestNum_);
    }
    if (value_ != 0) {
      output.writeInt32(5, value_);
    }
    if (((bitField0_ & 0x00000001) != 0)) {
      output.writeMessage(6, getTimestamp());
    }
    for (int i = 0; i < reportQuorum_.size(); i++) {
      output.writeMessage(7, reportQuorum_.get(i));
    }
    if (!requestDummy_.isEmpty()) {
      output.writeBytes(8, requestDummy_);
    }
    if (computeFactor_ != 0) {
      output.writeInt32(9, computeFactor_);
    }
    if (replySize_ != 0) {
      output.writeInt32(10, replySize_);
    }
    if (earlyExecResult_ != 0) {
      output.writeInt32(11, earlyExecResult_);
    }
    if (isTnxValid_ != false) {
      output.writeBool(12, isTnxValid_);
    }
    if (currentVersion_ != 0L) {
      output.writeInt64(13, currentVersion_);
    }
    for (int i = 0; i < reqLists_.size(); i++) {
      output.writeMessage(14, reqLists_.get(i));
    }
    for (int i = 0; i < readSet_.size(); i++) {
      output.writeMessage(15, readSet_.get(i));
    }
    for (int i = 0; i < writeSet_.size(); i++) {
      output.writeMessage(16, writeSet_.get(i));
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (client_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(1, client_);
    }
    if (requestNum_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(2, requestNum_);
    }
    if (value_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(5, value_);
    }
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(6, getTimestamp());
    }
    for (int i = 0; i < reportQuorum_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(7, reportQuorum_.get(i));
    }
    if (!requestDummy_.isEmpty()) {
      size += com.google.protobuf.CodedOutputStream
        .computeBytesSize(8, requestDummy_);
    }
    if (computeFactor_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(9, computeFactor_);
    }
    if (replySize_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(10, replySize_);
    }
    if (earlyExecResult_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(11, earlyExecResult_);
    }
    if (isTnxValid_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(12, isTnxValid_);
    }
    if (currentVersion_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(13, currentVersion_);
    }
    for (int i = 0; i < reqLists_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(14, reqLists_.get(i));
    }
    for (int i = 0; i < readSet_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(15, readSet_.get(i));
    }
    for (int i = 0; i < writeSet_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(16, writeSet_.get(i));
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.gbft.framework.data.RequestData)) {
      return super.equals(obj);
    }
    com.gbft.framework.data.RequestData other = (com.gbft.framework.data.RequestData) obj;

    if (getClient()
        != other.getClient()) return false;
    if (getRequestNum()
        != other.getRequestNum()) return false;
    if (getValue()
        != other.getValue()) return false;
    if (!getReadSetList()
        .equals(other.getReadSetList())) return false;
    if (!getWriteSetList()
        .equals(other.getWriteSetList())) return false;
    if (hasTimestamp() != other.hasTimestamp()) return false;
    if (hasTimestamp()) {
      if (!getTimestamp()
          .equals(other.getTimestamp())) return false;
    }
    if (!getReportQuorumList()
        .equals(other.getReportQuorumList())) return false;
    if (!getRequestDummy()
        .equals(other.getRequestDummy())) return false;
    if (getComputeFactor()
        != other.getComputeFactor()) return false;
    if (getReplySize()
        != other.getReplySize()) return false;
    if (getEarlyExecResult()
        != other.getEarlyExecResult()) return false;
    if (getIsTnxValid()
        != other.getIsTnxValid()) return false;
    if (getCurrentVersion()
        != other.getCurrentVersion()) return false;
    if (!getReqListsList()
        .equals(other.getReqListsList())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + CLIENT_FIELD_NUMBER;
    hash = (53 * hash) + getClient();
    hash = (37 * hash) + REQUEST_NUM_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getRequestNum());
    hash = (37 * hash) + VALUE_FIELD_NUMBER;
    hash = (53 * hash) + getValue();
    if (getReadSetCount() > 0) {
      hash = (37 * hash) + READ_SET_FIELD_NUMBER;
      hash = (53 * hash) + getReadSetList().hashCode();
    }
    if (getWriteSetCount() > 0) {
      hash = (37 * hash) + WRITE_SET_FIELD_NUMBER;
      hash = (53 * hash) + getWriteSetList().hashCode();
    }
    if (hasTimestamp()) {
      hash = (37 * hash) + TIMESTAMP_FIELD_NUMBER;
      hash = (53 * hash) + getTimestamp().hashCode();
    }
    if (getReportQuorumCount() > 0) {
      hash = (37 * hash) + REPORT_QUORUM_FIELD_NUMBER;
      hash = (53 * hash) + getReportQuorumList().hashCode();
    }
    hash = (37 * hash) + REQUEST_DUMMY_FIELD_NUMBER;
    hash = (53 * hash) + getRequestDummy().hashCode();
    hash = (37 * hash) + COMPUTE_FACTOR_FIELD_NUMBER;
    hash = (53 * hash) + getComputeFactor();
    hash = (37 * hash) + REPLY_SIZE_FIELD_NUMBER;
    hash = (53 * hash) + getReplySize();
    hash = (37 * hash) + EARLY_EXEC_RESULT_FIELD_NUMBER;
    hash = (53 * hash) + getEarlyExecResult();
    hash = (37 * hash) + IS_TNX_VALID_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getIsTnxValid());
    hash = (37 * hash) + CURRENT_VERSION_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getCurrentVersion());
    if (getReqListsCount() > 0) {
      hash = (37 * hash) + REQLISTS_FIELD_NUMBER;
      hash = (53 * hash) + getReqListsList().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.gbft.framework.data.RequestData parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.gbft.framework.data.RequestData parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.gbft.framework.data.RequestData parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.gbft.framework.data.RequestData parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.gbft.framework.data.RequestData parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.gbft.framework.data.RequestData parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.gbft.framework.data.RequestData parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.gbft.framework.data.RequestData parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.gbft.framework.data.RequestData parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.gbft.framework.data.RequestData parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.gbft.framework.data.RequestData parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.gbft.framework.data.RequestData parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.gbft.framework.data.RequestData prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code RequestData}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:RequestData)
      com.gbft.framework.data.RequestDataOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.gbft.framework.data.Gbft.internal_static_RequestData_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.gbft.framework.data.Gbft.internal_static_RequestData_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.gbft.framework.data.RequestData.class, com.gbft.framework.data.RequestData.Builder.class);
    }

    // Construct using com.gbft.framework.data.RequestData.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessage
              .alwaysUseFieldBuilders) {
        getReadSetFieldBuilder();
        getWriteSetFieldBuilder();
        getTimestampFieldBuilder();
        getReportQuorumFieldBuilder();
        getReqListsFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      client_ = 0;
      requestNum_ = 0L;
      value_ = 0;
      if (readSetBuilder_ == null) {
        readSet_ = java.util.Collections.emptyList();
      } else {
        readSet_ = null;
        readSetBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000008);
      if (writeSetBuilder_ == null) {
        writeSet_ = java.util.Collections.emptyList();
      } else {
        writeSet_ = null;
        writeSetBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000010);
      timestamp_ = null;
      if (timestampBuilder_ != null) {
        timestampBuilder_.dispose();
        timestampBuilder_ = null;
      }
      if (reportQuorumBuilder_ == null) {
        reportQuorum_ = java.util.Collections.emptyList();
      } else {
        reportQuorum_ = null;
        reportQuorumBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000040);
      requestDummy_ = com.google.protobuf.ByteString.EMPTY;
      computeFactor_ = 0;
      replySize_ = 0;
      earlyExecResult_ = 0;
      isTnxValid_ = false;
      currentVersion_ = 0L;
      if (reqListsBuilder_ == null) {
        reqLists_ = java.util.Collections.emptyList();
      } else {
        reqLists_ = null;
        reqListsBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00002000);
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.gbft.framework.data.Gbft.internal_static_RequestData_descriptor;
    }

    @java.lang.Override
    public com.gbft.framework.data.RequestData getDefaultInstanceForType() {
      return com.gbft.framework.data.RequestData.getDefaultInstance();
    }

    @java.lang.Override
    public com.gbft.framework.data.RequestData build() {
      com.gbft.framework.data.RequestData result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.gbft.framework.data.RequestData buildPartial() {
      com.gbft.framework.data.RequestData result = new com.gbft.framework.data.RequestData(this);
      buildPartialRepeatedFields(result);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartialRepeatedFields(com.gbft.framework.data.RequestData result) {
      if (readSetBuilder_ == null) {
        if (((bitField0_ & 0x00000008) != 0)) {
          readSet_ = java.util.Collections.unmodifiableList(readSet_);
          bitField0_ = (bitField0_ & ~0x00000008);
        }
        result.readSet_ = readSet_;
      } else {
        result.readSet_ = readSetBuilder_.build();
      }
      if (writeSetBuilder_ == null) {
        if (((bitField0_ & 0x00000010) != 0)) {
          writeSet_ = java.util.Collections.unmodifiableList(writeSet_);
          bitField0_ = (bitField0_ & ~0x00000010);
        }
        result.writeSet_ = writeSet_;
      } else {
        result.writeSet_ = writeSetBuilder_.build();
      }
      if (reportQuorumBuilder_ == null) {
        if (((bitField0_ & 0x00000040) != 0)) {
          reportQuorum_ = java.util.Collections.unmodifiableList(reportQuorum_);
          bitField0_ = (bitField0_ & ~0x00000040);
        }
        result.reportQuorum_ = reportQuorum_;
      } else {
        result.reportQuorum_ = reportQuorumBuilder_.build();
      }
      if (reqListsBuilder_ == null) {
        if (((bitField0_ & 0x00002000) != 0)) {
          reqLists_ = java.util.Collections.unmodifiableList(reqLists_);
          bitField0_ = (bitField0_ & ~0x00002000);
        }
        result.reqLists_ = reqLists_;
      } else {
        result.reqLists_ = reqListsBuilder_.build();
      }
    }

    private void buildPartial0(com.gbft.framework.data.RequestData result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.client_ = client_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.requestNum_ = requestNum_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.value_ = value_;
      }
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000020) != 0)) {
        result.timestamp_ = timestampBuilder_ == null
            ? timestamp_
            : timestampBuilder_.build();
        to_bitField0_ |= 0x00000001;
      }
      if (((from_bitField0_ & 0x00000080) != 0)) {
        result.requestDummy_ = requestDummy_;
      }
      if (((from_bitField0_ & 0x00000100) != 0)) {
        result.computeFactor_ = computeFactor_;
      }
      if (((from_bitField0_ & 0x00000200) != 0)) {
        result.replySize_ = replySize_;
      }
      if (((from_bitField0_ & 0x00000400) != 0)) {
        result.earlyExecResult_ = earlyExecResult_;
      }
      if (((from_bitField0_ & 0x00000800) != 0)) {
        result.isTnxValid_ = isTnxValid_;
      }
      if (((from_bitField0_ & 0x00001000) != 0)) {
        result.currentVersion_ = currentVersion_;
      }
      result.bitField0_ |= to_bitField0_;
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.gbft.framework.data.RequestData) {
        return mergeFrom((com.gbft.framework.data.RequestData)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.gbft.framework.data.RequestData other) {
      if (other == com.gbft.framework.data.RequestData.getDefaultInstance()) return this;
      if (other.getClient() != 0) {
        setClient(other.getClient());
      }
      if (other.getRequestNum() != 0L) {
        setRequestNum(other.getRequestNum());
      }
      if (other.getValue() != 0) {
        setValue(other.getValue());
      }
      if (readSetBuilder_ == null) {
        if (!other.readSet_.isEmpty()) {
          if (readSet_.isEmpty()) {
            readSet_ = other.readSet_;
            bitField0_ = (bitField0_ & ~0x00000008);
          } else {
            ensureReadSetIsMutable();
            readSet_.addAll(other.readSet_);
          }
          onChanged();
        }
      } else {
        if (!other.readSet_.isEmpty()) {
          if (readSetBuilder_.isEmpty()) {
            readSetBuilder_.dispose();
            readSetBuilder_ = null;
            readSet_ = other.readSet_;
            bitField0_ = (bitField0_ & ~0x00000008);
            readSetBuilder_ = 
              com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                 getReadSetFieldBuilder() : null;
          } else {
            readSetBuilder_.addAllMessages(other.readSet_);
          }
        }
      }
      if (writeSetBuilder_ == null) {
        if (!other.writeSet_.isEmpty()) {
          if (writeSet_.isEmpty()) {
            writeSet_ = other.writeSet_;
            bitField0_ = (bitField0_ & ~0x00000010);
          } else {
            ensureWriteSetIsMutable();
            writeSet_.addAll(other.writeSet_);
          }
          onChanged();
        }
      } else {
        if (!other.writeSet_.isEmpty()) {
          if (writeSetBuilder_.isEmpty()) {
            writeSetBuilder_.dispose();
            writeSetBuilder_ = null;
            writeSet_ = other.writeSet_;
            bitField0_ = (bitField0_ & ~0x00000010);
            writeSetBuilder_ = 
              com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                 getWriteSetFieldBuilder() : null;
          } else {
            writeSetBuilder_.addAllMessages(other.writeSet_);
          }
        }
      }
      if (other.hasTimestamp()) {
        mergeTimestamp(other.getTimestamp());
      }
      if (reportQuorumBuilder_ == null) {
        if (!other.reportQuorum_.isEmpty()) {
          if (reportQuorum_.isEmpty()) {
            reportQuorum_ = other.reportQuorum_;
            bitField0_ = (bitField0_ & ~0x00000040);
          } else {
            ensureReportQuorumIsMutable();
            reportQuorum_.addAll(other.reportQuorum_);
          }
          onChanged();
        }
      } else {
        if (!other.reportQuorum_.isEmpty()) {
          if (reportQuorumBuilder_.isEmpty()) {
            reportQuorumBuilder_.dispose();
            reportQuorumBuilder_ = null;
            reportQuorum_ = other.reportQuorum_;
            bitField0_ = (bitField0_ & ~0x00000040);
            reportQuorumBuilder_ = 
              com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                 getReportQuorumFieldBuilder() : null;
          } else {
            reportQuorumBuilder_.addAllMessages(other.reportQuorum_);
          }
        }
      }
      if (other.getRequestDummy() != com.google.protobuf.ByteString.EMPTY) {
        setRequestDummy(other.getRequestDummy());
      }
      if (other.getComputeFactor() != 0) {
        setComputeFactor(other.getComputeFactor());
      }
      if (other.getReplySize() != 0) {
        setReplySize(other.getReplySize());
      }
      if (other.getEarlyExecResult() != 0) {
        setEarlyExecResult(other.getEarlyExecResult());
      }
      if (other.getIsTnxValid() != false) {
        setIsTnxValid(other.getIsTnxValid());
      }
      if (other.getCurrentVersion() != 0L) {
        setCurrentVersion(other.getCurrentVersion());
      }
      if (reqListsBuilder_ == null) {
        if (!other.reqLists_.isEmpty()) {
          if (reqLists_.isEmpty()) {
            reqLists_ = other.reqLists_;
            bitField0_ = (bitField0_ & ~0x00002000);
          } else {
            ensureReqListsIsMutable();
            reqLists_.addAll(other.reqLists_);
          }
          onChanged();
        }
      } else {
        if (!other.reqLists_.isEmpty()) {
          if (reqListsBuilder_.isEmpty()) {
            reqListsBuilder_.dispose();
            reqListsBuilder_ = null;
            reqLists_ = other.reqLists_;
            bitField0_ = (bitField0_ & ~0x00002000);
            reqListsBuilder_ = 
              com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                 getReqListsFieldBuilder() : null;
          } else {
            reqListsBuilder_.addAllMessages(other.reqLists_);
          }
        }
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              client_ = input.readInt32();
              bitField0_ |= 0x00000001;
              break;
            } // case 8
            case 16: {
              requestNum_ = input.readInt64();
              bitField0_ |= 0x00000002;
              break;
            } // case 16
            case 40: {
              value_ = input.readInt32();
              bitField0_ |= 0x00000004;
              break;
            } // case 40
            case 50: {
              input.readMessage(
                  getTimestampFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000020;
              break;
            } // case 50
            case 58: {
              com.gbft.framework.data.LearningData m =
                  input.readMessage(
                      com.gbft.framework.data.LearningData.parser(),
                      extensionRegistry);
              if (reportQuorumBuilder_ == null) {
                ensureReportQuorumIsMutable();
                reportQuorum_.add(m);
              } else {
                reportQuorumBuilder_.addMessage(m);
              }
              break;
            } // case 58
            case 66: {
              requestDummy_ = input.readBytes();
              bitField0_ |= 0x00000080;
              break;
            } // case 66
            case 72: {
              computeFactor_ = input.readInt32();
              bitField0_ |= 0x00000100;
              break;
            } // case 72
            case 80: {
              replySize_ = input.readInt32();
              bitField0_ |= 0x00000200;
              break;
            } // case 80
            case 88: {
              earlyExecResult_ = input.readInt32();
              bitField0_ |= 0x00000400;
              break;
            } // case 88
            case 96: {
              isTnxValid_ = input.readBool();
              bitField0_ |= 0x00000800;
              break;
            } // case 96
            case 104: {
              currentVersion_ = input.readInt64();
              bitField0_ |= 0x00001000;
              break;
            } // case 104
            case 114: {
              com.gbft.framework.data.RequestDataList m =
                  input.readMessage(
                      com.gbft.framework.data.RequestDataList.parser(),
                      extensionRegistry);
              if (reqListsBuilder_ == null) {
                ensureReqListsIsMutable();
                reqLists_.add(m);
              } else {
                reqListsBuilder_.addMessage(m);
              }
              break;
            } // case 114
            case 122: {
              com.gbft.framework.data.OperationSet m =
                  input.readMessage(
                      com.gbft.framework.data.OperationSet.parser(),
                      extensionRegistry);
              if (readSetBuilder_ == null) {
                ensureReadSetIsMutable();
                readSet_.add(m);
              } else {
                readSetBuilder_.addMessage(m);
              }
              break;
            } // case 122
            case 130: {
              com.gbft.framework.data.OperationSet m =
                  input.readMessage(
                      com.gbft.framework.data.OperationSet.parser(),
                      extensionRegistry);
              if (writeSetBuilder_ == null) {
                ensureWriteSetIsMutable();
                writeSet_.add(m);
              } else {
                writeSetBuilder_.addMessage(m);
              }
              break;
            } // case 130
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private int client_ ;
    /**
     * <code>int32 client = 1;</code>
     * @return The client.
     */
    @java.lang.Override
    public int getClient() {
      return client_;
    }
    /**
     * <code>int32 client = 1;</code>
     * @param value The client to set.
     * @return This builder for chaining.
     */
    public Builder setClient(int value) {

      client_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>int32 client = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearClient() {
      bitField0_ = (bitField0_ & ~0x00000001);
      client_ = 0;
      onChanged();
      return this;
    }

    private long requestNum_ ;
    /**
     * <code>int64 request_num = 2;</code>
     * @return The requestNum.
     */
    @java.lang.Override
    public long getRequestNum() {
      return requestNum_;
    }
    /**
     * <code>int64 request_num = 2;</code>
     * @param value The requestNum to set.
     * @return This builder for chaining.
     */
    public Builder setRequestNum(long value) {

      requestNum_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>int64 request_num = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearRequestNum() {
      bitField0_ = (bitField0_ & ~0x00000002);
      requestNum_ = 0L;
      onChanged();
      return this;
    }

    private int value_ ;
    /**
     * <pre>
     * int32 record = 3;
     * Operation operation = 4;
     * </pre>
     *
     * <code>int32 value = 5;</code>
     * @return The value.
     */
    @java.lang.Override
    public int getValue() {
      return value_;
    }
    /**
     * <pre>
     * int32 record = 3;
     * Operation operation = 4;
     * </pre>
     *
     * <code>int32 value = 5;</code>
     * @param value The value to set.
     * @return This builder for chaining.
     */
    public Builder setValue(int value) {

      value_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * int32 record = 3;
     * Operation operation = 4;
     * </pre>
     *
     * <code>int32 value = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearValue() {
      bitField0_ = (bitField0_ & ~0x00000004);
      value_ = 0;
      onChanged();
      return this;
    }

    private java.util.List<com.gbft.framework.data.OperationSet> readSet_ =
      java.util.Collections.emptyList();
    private void ensureReadSetIsMutable() {
      if (!((bitField0_ & 0x00000008) != 0)) {
        readSet_ = new java.util.ArrayList<com.gbft.framework.data.OperationSet>(readSet_);
        bitField0_ |= 0x00000008;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilder<
        com.gbft.framework.data.OperationSet, com.gbft.framework.data.OperationSet.Builder, com.gbft.framework.data.OperationSetOrBuilder> readSetBuilder_;

    /**
     * <code>repeated .OperationSet read_set = 15;</code>
     */
    public java.util.List<com.gbft.framework.data.OperationSet> getReadSetList() {
      if (readSetBuilder_ == null) {
        return java.util.Collections.unmodifiableList(readSet_);
      } else {
        return readSetBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .OperationSet read_set = 15;</code>
     */
    public int getReadSetCount() {
      if (readSetBuilder_ == null) {
        return readSet_.size();
      } else {
        return readSetBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .OperationSet read_set = 15;</code>
     */
    public com.gbft.framework.data.OperationSet getReadSet(int index) {
      if (readSetBuilder_ == null) {
        return readSet_.get(index);
      } else {
        return readSetBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .OperationSet read_set = 15;</code>
     */
    public Builder setReadSet(
        int index, com.gbft.framework.data.OperationSet value) {
      if (readSetBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureReadSetIsMutable();
        readSet_.set(index, value);
        onChanged();
      } else {
        readSetBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .OperationSet read_set = 15;</code>
     */
    public Builder setReadSet(
        int index, com.gbft.framework.data.OperationSet.Builder builderForValue) {
      if (readSetBuilder_ == null) {
        ensureReadSetIsMutable();
        readSet_.set(index, builderForValue.build());
        onChanged();
      } else {
        readSetBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .OperationSet read_set = 15;</code>
     */
    public Builder addReadSet(com.gbft.framework.data.OperationSet value) {
      if (readSetBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureReadSetIsMutable();
        readSet_.add(value);
        onChanged();
      } else {
        readSetBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .OperationSet read_set = 15;</code>
     */
    public Builder addReadSet(
        int index, com.gbft.framework.data.OperationSet value) {
      if (readSetBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureReadSetIsMutable();
        readSet_.add(index, value);
        onChanged();
      } else {
        readSetBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .OperationSet read_set = 15;</code>
     */
    public Builder addReadSet(
        com.gbft.framework.data.OperationSet.Builder builderForValue) {
      if (readSetBuilder_ == null) {
        ensureReadSetIsMutable();
        readSet_.add(builderForValue.build());
        onChanged();
      } else {
        readSetBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .OperationSet read_set = 15;</code>
     */
    public Builder addReadSet(
        int index, com.gbft.framework.data.OperationSet.Builder builderForValue) {
      if (readSetBuilder_ == null) {
        ensureReadSetIsMutable();
        readSet_.add(index, builderForValue.build());
        onChanged();
      } else {
        readSetBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .OperationSet read_set = 15;</code>
     */
    public Builder addAllReadSet(
        java.lang.Iterable<? extends com.gbft.framework.data.OperationSet> values) {
      if (readSetBuilder_ == null) {
        ensureReadSetIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, readSet_);
        onChanged();
      } else {
        readSetBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .OperationSet read_set = 15;</code>
     */
    public Builder clearReadSet() {
      if (readSetBuilder_ == null) {
        readSet_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000008);
        onChanged();
      } else {
        readSetBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .OperationSet read_set = 15;</code>
     */
    public Builder removeReadSet(int index) {
      if (readSetBuilder_ == null) {
        ensureReadSetIsMutable();
        readSet_.remove(index);
        onChanged();
      } else {
        readSetBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .OperationSet read_set = 15;</code>
     */
    public com.gbft.framework.data.OperationSet.Builder getReadSetBuilder(
        int index) {
      return getReadSetFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .OperationSet read_set = 15;</code>
     */
    public com.gbft.framework.data.OperationSetOrBuilder getReadSetOrBuilder(
        int index) {
      if (readSetBuilder_ == null) {
        return readSet_.get(index);  } else {
        return readSetBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .OperationSet read_set = 15;</code>
     */
    public java.util.List<? extends com.gbft.framework.data.OperationSetOrBuilder> 
         getReadSetOrBuilderList() {
      if (readSetBuilder_ != null) {
        return readSetBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(readSet_);
      }
    }
    /**
     * <code>repeated .OperationSet read_set = 15;</code>
     */
    public com.gbft.framework.data.OperationSet.Builder addReadSetBuilder() {
      return getReadSetFieldBuilder().addBuilder(
          com.gbft.framework.data.OperationSet.getDefaultInstance());
    }
    /**
     * <code>repeated .OperationSet read_set = 15;</code>
     */
    public com.gbft.framework.data.OperationSet.Builder addReadSetBuilder(
        int index) {
      return getReadSetFieldBuilder().addBuilder(
          index, com.gbft.framework.data.OperationSet.getDefaultInstance());
    }
    /**
     * <code>repeated .OperationSet read_set = 15;</code>
     */
    public java.util.List<com.gbft.framework.data.OperationSet.Builder> 
         getReadSetBuilderList() {
      return getReadSetFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilder<
        com.gbft.framework.data.OperationSet, com.gbft.framework.data.OperationSet.Builder, com.gbft.framework.data.OperationSetOrBuilder> 
        getReadSetFieldBuilder() {
      if (readSetBuilder_ == null) {
        readSetBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
            com.gbft.framework.data.OperationSet, com.gbft.framework.data.OperationSet.Builder, com.gbft.framework.data.OperationSetOrBuilder>(
                readSet_,
                ((bitField0_ & 0x00000008) != 0),
                getParentForChildren(),
                isClean());
        readSet_ = null;
      }
      return readSetBuilder_;
    }

    private java.util.List<com.gbft.framework.data.OperationSet> writeSet_ =
      java.util.Collections.emptyList();
    private void ensureWriteSetIsMutable() {
      if (!((bitField0_ & 0x00000010) != 0)) {
        writeSet_ = new java.util.ArrayList<com.gbft.framework.data.OperationSet>(writeSet_);
        bitField0_ |= 0x00000010;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilder<
        com.gbft.framework.data.OperationSet, com.gbft.framework.data.OperationSet.Builder, com.gbft.framework.data.OperationSetOrBuilder> writeSetBuilder_;

    /**
     * <code>repeated .OperationSet write_set = 16;</code>
     */
    public java.util.List<com.gbft.framework.data.OperationSet> getWriteSetList() {
      if (writeSetBuilder_ == null) {
        return java.util.Collections.unmodifiableList(writeSet_);
      } else {
        return writeSetBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .OperationSet write_set = 16;</code>
     */
    public int getWriteSetCount() {
      if (writeSetBuilder_ == null) {
        return writeSet_.size();
      } else {
        return writeSetBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .OperationSet write_set = 16;</code>
     */
    public com.gbft.framework.data.OperationSet getWriteSet(int index) {
      if (writeSetBuilder_ == null) {
        return writeSet_.get(index);
      } else {
        return writeSetBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .OperationSet write_set = 16;</code>
     */
    public Builder setWriteSet(
        int index, com.gbft.framework.data.OperationSet value) {
      if (writeSetBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureWriteSetIsMutable();
        writeSet_.set(index, value);
        onChanged();
      } else {
        writeSetBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .OperationSet write_set = 16;</code>
     */
    public Builder setWriteSet(
        int index, com.gbft.framework.data.OperationSet.Builder builderForValue) {
      if (writeSetBuilder_ == null) {
        ensureWriteSetIsMutable();
        writeSet_.set(index, builderForValue.build());
        onChanged();
      } else {
        writeSetBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .OperationSet write_set = 16;</code>
     */
    public Builder addWriteSet(com.gbft.framework.data.OperationSet value) {
      if (writeSetBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureWriteSetIsMutable();
        writeSet_.add(value);
        onChanged();
      } else {
        writeSetBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .OperationSet write_set = 16;</code>
     */
    public Builder addWriteSet(
        int index, com.gbft.framework.data.OperationSet value) {
      if (writeSetBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureWriteSetIsMutable();
        writeSet_.add(index, value);
        onChanged();
      } else {
        writeSetBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .OperationSet write_set = 16;</code>
     */
    public Builder addWriteSet(
        com.gbft.framework.data.OperationSet.Builder builderForValue) {
      if (writeSetBuilder_ == null) {
        ensureWriteSetIsMutable();
        writeSet_.add(builderForValue.build());
        onChanged();
      } else {
        writeSetBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .OperationSet write_set = 16;</code>
     */
    public Builder addWriteSet(
        int index, com.gbft.framework.data.OperationSet.Builder builderForValue) {
      if (writeSetBuilder_ == null) {
        ensureWriteSetIsMutable();
        writeSet_.add(index, builderForValue.build());
        onChanged();
      } else {
        writeSetBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .OperationSet write_set = 16;</code>
     */
    public Builder addAllWriteSet(
        java.lang.Iterable<? extends com.gbft.framework.data.OperationSet> values) {
      if (writeSetBuilder_ == null) {
        ensureWriteSetIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, writeSet_);
        onChanged();
      } else {
        writeSetBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .OperationSet write_set = 16;</code>
     */
    public Builder clearWriteSet() {
      if (writeSetBuilder_ == null) {
        writeSet_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000010);
        onChanged();
      } else {
        writeSetBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .OperationSet write_set = 16;</code>
     */
    public Builder removeWriteSet(int index) {
      if (writeSetBuilder_ == null) {
        ensureWriteSetIsMutable();
        writeSet_.remove(index);
        onChanged();
      } else {
        writeSetBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .OperationSet write_set = 16;</code>
     */
    public com.gbft.framework.data.OperationSet.Builder getWriteSetBuilder(
        int index) {
      return getWriteSetFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .OperationSet write_set = 16;</code>
     */
    public com.gbft.framework.data.OperationSetOrBuilder getWriteSetOrBuilder(
        int index) {
      if (writeSetBuilder_ == null) {
        return writeSet_.get(index);  } else {
        return writeSetBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .OperationSet write_set = 16;</code>
     */
    public java.util.List<? extends com.gbft.framework.data.OperationSetOrBuilder> 
         getWriteSetOrBuilderList() {
      if (writeSetBuilder_ != null) {
        return writeSetBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(writeSet_);
      }
    }
    /**
     * <code>repeated .OperationSet write_set = 16;</code>
     */
    public com.gbft.framework.data.OperationSet.Builder addWriteSetBuilder() {
      return getWriteSetFieldBuilder().addBuilder(
          com.gbft.framework.data.OperationSet.getDefaultInstance());
    }
    /**
     * <code>repeated .OperationSet write_set = 16;</code>
     */
    public com.gbft.framework.data.OperationSet.Builder addWriteSetBuilder(
        int index) {
      return getWriteSetFieldBuilder().addBuilder(
          index, com.gbft.framework.data.OperationSet.getDefaultInstance());
    }
    /**
     * <code>repeated .OperationSet write_set = 16;</code>
     */
    public java.util.List<com.gbft.framework.data.OperationSet.Builder> 
         getWriteSetBuilderList() {
      return getWriteSetFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilder<
        com.gbft.framework.data.OperationSet, com.gbft.framework.data.OperationSet.Builder, com.gbft.framework.data.OperationSetOrBuilder> 
        getWriteSetFieldBuilder() {
      if (writeSetBuilder_ == null) {
        writeSetBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
            com.gbft.framework.data.OperationSet, com.gbft.framework.data.OperationSet.Builder, com.gbft.framework.data.OperationSetOrBuilder>(
                writeSet_,
                ((bitField0_ & 0x00000010) != 0),
                getParentForChildren(),
                isClean());
        writeSet_ = null;
      }
      return writeSetBuilder_;
    }

    private com.google.protobuf.Timestamp timestamp_;
    private com.google.protobuf.SingleFieldBuilder<
        com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> timestampBuilder_;
    /**
     * <code>.google.protobuf.Timestamp timestamp = 6;</code>
     * @return Whether the timestamp field is set.
     */
    public boolean hasTimestamp() {
      return ((bitField0_ & 0x00000020) != 0);
    }
    /**
     * <code>.google.protobuf.Timestamp timestamp = 6;</code>
     * @return The timestamp.
     */
    public com.google.protobuf.Timestamp getTimestamp() {
      if (timestampBuilder_ == null) {
        return timestamp_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : timestamp_;
      } else {
        return timestampBuilder_.getMessage();
      }
    }
    /**
     * <code>.google.protobuf.Timestamp timestamp = 6;</code>
     */
    public Builder setTimestamp(com.google.protobuf.Timestamp value) {
      if (timestampBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        timestamp_ = value;
      } else {
        timestampBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000020;
      onChanged();
      return this;
    }
    /**
     * <code>.google.protobuf.Timestamp timestamp = 6;</code>
     */
    public Builder setTimestamp(
        com.google.protobuf.Timestamp.Builder builderForValue) {
      if (timestampBuilder_ == null) {
        timestamp_ = builderForValue.build();
      } else {
        timestampBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000020;
      onChanged();
      return this;
    }
    /**
     * <code>.google.protobuf.Timestamp timestamp = 6;</code>
     */
    public Builder mergeTimestamp(com.google.protobuf.Timestamp value) {
      if (timestampBuilder_ == null) {
        if (((bitField0_ & 0x00000020) != 0) &&
          timestamp_ != null &&
          timestamp_ != com.google.protobuf.Timestamp.getDefaultInstance()) {
          getTimestampBuilder().mergeFrom(value);
        } else {
          timestamp_ = value;
        }
      } else {
        timestampBuilder_.mergeFrom(value);
      }
      if (timestamp_ != null) {
        bitField0_ |= 0x00000020;
        onChanged();
      }
      return this;
    }
    /**
     * <code>.google.protobuf.Timestamp timestamp = 6;</code>
     */
    public Builder clearTimestamp() {
      bitField0_ = (bitField0_ & ~0x00000020);
      timestamp_ = null;
      if (timestampBuilder_ != null) {
        timestampBuilder_.dispose();
        timestampBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>.google.protobuf.Timestamp timestamp = 6;</code>
     */
    public com.google.protobuf.Timestamp.Builder getTimestampBuilder() {
      bitField0_ |= 0x00000020;
      onChanged();
      return getTimestampFieldBuilder().getBuilder();
    }
    /**
     * <code>.google.protobuf.Timestamp timestamp = 6;</code>
     */
    public com.google.protobuf.TimestampOrBuilder getTimestampOrBuilder() {
      if (timestampBuilder_ != null) {
        return timestampBuilder_.getMessageOrBuilder();
      } else {
        return timestamp_ == null ?
            com.google.protobuf.Timestamp.getDefaultInstance() : timestamp_;
      }
    }
    /**
     * <code>.google.protobuf.Timestamp timestamp = 6;</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
        com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> 
        getTimestampFieldBuilder() {
      if (timestampBuilder_ == null) {
        timestampBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder>(
                getTimestamp(),
                getParentForChildren(),
                isClean());
        timestamp_ = null;
      }
      return timestampBuilder_;
    }

    private java.util.List<com.gbft.framework.data.LearningData> reportQuorum_ =
      java.util.Collections.emptyList();
    private void ensureReportQuorumIsMutable() {
      if (!((bitField0_ & 0x00000040) != 0)) {
        reportQuorum_ = new java.util.ArrayList<com.gbft.framework.data.LearningData>(reportQuorum_);
        bitField0_ |= 0x00000040;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilder<
        com.gbft.framework.data.LearningData, com.gbft.framework.data.LearningData.Builder, com.gbft.framework.data.LearningDataOrBuilder> reportQuorumBuilder_;

    /**
     * <code>repeated .LearningData report_quorum = 7;</code>
     */
    public java.util.List<com.gbft.framework.data.LearningData> getReportQuorumList() {
      if (reportQuorumBuilder_ == null) {
        return java.util.Collections.unmodifiableList(reportQuorum_);
      } else {
        return reportQuorumBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .LearningData report_quorum = 7;</code>
     */
    public int getReportQuorumCount() {
      if (reportQuorumBuilder_ == null) {
        return reportQuorum_.size();
      } else {
        return reportQuorumBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .LearningData report_quorum = 7;</code>
     */
    public com.gbft.framework.data.LearningData getReportQuorum(int index) {
      if (reportQuorumBuilder_ == null) {
        return reportQuorum_.get(index);
      } else {
        return reportQuorumBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .LearningData report_quorum = 7;</code>
     */
    public Builder setReportQuorum(
        int index, com.gbft.framework.data.LearningData value) {
      if (reportQuorumBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureReportQuorumIsMutable();
        reportQuorum_.set(index, value);
        onChanged();
      } else {
        reportQuorumBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .LearningData report_quorum = 7;</code>
     */
    public Builder setReportQuorum(
        int index, com.gbft.framework.data.LearningData.Builder builderForValue) {
      if (reportQuorumBuilder_ == null) {
        ensureReportQuorumIsMutable();
        reportQuorum_.set(index, builderForValue.build());
        onChanged();
      } else {
        reportQuorumBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .LearningData report_quorum = 7;</code>
     */
    public Builder addReportQuorum(com.gbft.framework.data.LearningData value) {
      if (reportQuorumBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureReportQuorumIsMutable();
        reportQuorum_.add(value);
        onChanged();
      } else {
        reportQuorumBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .LearningData report_quorum = 7;</code>
     */
    public Builder addReportQuorum(
        int index, com.gbft.framework.data.LearningData value) {
      if (reportQuorumBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureReportQuorumIsMutable();
        reportQuorum_.add(index, value);
        onChanged();
      } else {
        reportQuorumBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .LearningData report_quorum = 7;</code>
     */
    public Builder addReportQuorum(
        com.gbft.framework.data.LearningData.Builder builderForValue) {
      if (reportQuorumBuilder_ == null) {
        ensureReportQuorumIsMutable();
        reportQuorum_.add(builderForValue.build());
        onChanged();
      } else {
        reportQuorumBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .LearningData report_quorum = 7;</code>
     */
    public Builder addReportQuorum(
        int index, com.gbft.framework.data.LearningData.Builder builderForValue) {
      if (reportQuorumBuilder_ == null) {
        ensureReportQuorumIsMutable();
        reportQuorum_.add(index, builderForValue.build());
        onChanged();
      } else {
        reportQuorumBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .LearningData report_quorum = 7;</code>
     */
    public Builder addAllReportQuorum(
        java.lang.Iterable<? extends com.gbft.framework.data.LearningData> values) {
      if (reportQuorumBuilder_ == null) {
        ensureReportQuorumIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, reportQuorum_);
        onChanged();
      } else {
        reportQuorumBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .LearningData report_quorum = 7;</code>
     */
    public Builder clearReportQuorum() {
      if (reportQuorumBuilder_ == null) {
        reportQuorum_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000040);
        onChanged();
      } else {
        reportQuorumBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .LearningData report_quorum = 7;</code>
     */
    public Builder removeReportQuorum(int index) {
      if (reportQuorumBuilder_ == null) {
        ensureReportQuorumIsMutable();
        reportQuorum_.remove(index);
        onChanged();
      } else {
        reportQuorumBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .LearningData report_quorum = 7;</code>
     */
    public com.gbft.framework.data.LearningData.Builder getReportQuorumBuilder(
        int index) {
      return getReportQuorumFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .LearningData report_quorum = 7;</code>
     */
    public com.gbft.framework.data.LearningDataOrBuilder getReportQuorumOrBuilder(
        int index) {
      if (reportQuorumBuilder_ == null) {
        return reportQuorum_.get(index);  } else {
        return reportQuorumBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .LearningData report_quorum = 7;</code>
     */
    public java.util.List<? extends com.gbft.framework.data.LearningDataOrBuilder> 
         getReportQuorumOrBuilderList() {
      if (reportQuorumBuilder_ != null) {
        return reportQuorumBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(reportQuorum_);
      }
    }
    /**
     * <code>repeated .LearningData report_quorum = 7;</code>
     */
    public com.gbft.framework.data.LearningData.Builder addReportQuorumBuilder() {
      return getReportQuorumFieldBuilder().addBuilder(
          com.gbft.framework.data.LearningData.getDefaultInstance());
    }
    /**
     * <code>repeated .LearningData report_quorum = 7;</code>
     */
    public com.gbft.framework.data.LearningData.Builder addReportQuorumBuilder(
        int index) {
      return getReportQuorumFieldBuilder().addBuilder(
          index, com.gbft.framework.data.LearningData.getDefaultInstance());
    }
    /**
     * <code>repeated .LearningData report_quorum = 7;</code>
     */
    public java.util.List<com.gbft.framework.data.LearningData.Builder> 
         getReportQuorumBuilderList() {
      return getReportQuorumFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilder<
        com.gbft.framework.data.LearningData, com.gbft.framework.data.LearningData.Builder, com.gbft.framework.data.LearningDataOrBuilder> 
        getReportQuorumFieldBuilder() {
      if (reportQuorumBuilder_ == null) {
        reportQuorumBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
            com.gbft.framework.data.LearningData, com.gbft.framework.data.LearningData.Builder, com.gbft.framework.data.LearningDataOrBuilder>(
                reportQuorum_,
                ((bitField0_ & 0x00000040) != 0),
                getParentForChildren(),
                isClean());
        reportQuorum_ = null;
      }
      return reportQuorumBuilder_;
    }

    private com.google.protobuf.ByteString requestDummy_ = com.google.protobuf.ByteString.EMPTY;
    /**
     * <code>bytes request_dummy = 8;</code>
     * @return The requestDummy.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getRequestDummy() {
      return requestDummy_;
    }
    /**
     * <code>bytes request_dummy = 8;</code>
     * @param value The requestDummy to set.
     * @return This builder for chaining.
     */
    public Builder setRequestDummy(com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      requestDummy_ = value;
      bitField0_ |= 0x00000080;
      onChanged();
      return this;
    }
    /**
     * <code>bytes request_dummy = 8;</code>
     * @return This builder for chaining.
     */
    public Builder clearRequestDummy() {
      bitField0_ = (bitField0_ & ~0x00000080);
      requestDummy_ = getDefaultInstance().getRequestDummy();
      onChanged();
      return this;
    }

    private int computeFactor_ ;
    /**
     * <code>int32 compute_factor = 9;</code>
     * @return The computeFactor.
     */
    @java.lang.Override
    public int getComputeFactor() {
      return computeFactor_;
    }
    /**
     * <code>int32 compute_factor = 9;</code>
     * @param value The computeFactor to set.
     * @return This builder for chaining.
     */
    public Builder setComputeFactor(int value) {

      computeFactor_ = value;
      bitField0_ |= 0x00000100;
      onChanged();
      return this;
    }
    /**
     * <code>int32 compute_factor = 9;</code>
     * @return This builder for chaining.
     */
    public Builder clearComputeFactor() {
      bitField0_ = (bitField0_ & ~0x00000100);
      computeFactor_ = 0;
      onChanged();
      return this;
    }

    private int replySize_ ;
    /**
     * <code>int32 reply_size = 10;</code>
     * @return The replySize.
     */
    @java.lang.Override
    public int getReplySize() {
      return replySize_;
    }
    /**
     * <code>int32 reply_size = 10;</code>
     * @param value The replySize to set.
     * @return This builder for chaining.
     */
    public Builder setReplySize(int value) {

      replySize_ = value;
      bitField0_ |= 0x00000200;
      onChanged();
      return this;
    }
    /**
     * <code>int32 reply_size = 10;</code>
     * @return This builder for chaining.
     */
    public Builder clearReplySize() {
      bitField0_ = (bitField0_ & ~0x00000200);
      replySize_ = 0;
      onChanged();
      return this;
    }

    private int earlyExecResult_ ;
    /**
     * <code>int32 early_exec_result = 11;</code>
     * @return The earlyExecResult.
     */
    @java.lang.Override
    public int getEarlyExecResult() {
      return earlyExecResult_;
    }
    /**
     * <code>int32 early_exec_result = 11;</code>
     * @param value The earlyExecResult to set.
     * @return This builder for chaining.
     */
    public Builder setEarlyExecResult(int value) {

      earlyExecResult_ = value;
      bitField0_ |= 0x00000400;
      onChanged();
      return this;
    }
    /**
     * <code>int32 early_exec_result = 11;</code>
     * @return This builder for chaining.
     */
    public Builder clearEarlyExecResult() {
      bitField0_ = (bitField0_ & ~0x00000400);
      earlyExecResult_ = 0;
      onChanged();
      return this;
    }

    private boolean isTnxValid_ ;
    /**
     * <code>bool is_tnx_valid = 12;</code>
     * @return The isTnxValid.
     */
    @java.lang.Override
    public boolean getIsTnxValid() {
      return isTnxValid_;
    }
    /**
     * <code>bool is_tnx_valid = 12;</code>
     * @param value The isTnxValid to set.
     * @return This builder for chaining.
     */
    public Builder setIsTnxValid(boolean value) {

      isTnxValid_ = value;
      bitField0_ |= 0x00000800;
      onChanged();
      return this;
    }
    /**
     * <code>bool is_tnx_valid = 12;</code>
     * @return This builder for chaining.
     */
    public Builder clearIsTnxValid() {
      bitField0_ = (bitField0_ & ~0x00000800);
      isTnxValid_ = false;
      onChanged();
      return this;
    }

    private long currentVersion_ ;
    /**
     * <code>int64 current_version = 13;</code>
     * @return The currentVersion.
     */
    @java.lang.Override
    public long getCurrentVersion() {
      return currentVersion_;
    }
    /**
     * <code>int64 current_version = 13;</code>
     * @param value The currentVersion to set.
     * @return This builder for chaining.
     */
    public Builder setCurrentVersion(long value) {

      currentVersion_ = value;
      bitField0_ |= 0x00001000;
      onChanged();
      return this;
    }
    /**
     * <code>int64 current_version = 13;</code>
     * @return This builder for chaining.
     */
    public Builder clearCurrentVersion() {
      bitField0_ = (bitField0_ & ~0x00001000);
      currentVersion_ = 0L;
      onChanged();
      return this;
    }

    private java.util.List<com.gbft.framework.data.RequestDataList> reqLists_ =
      java.util.Collections.emptyList();
    private void ensureReqListsIsMutable() {
      if (!((bitField0_ & 0x00002000) != 0)) {
        reqLists_ = new java.util.ArrayList<com.gbft.framework.data.RequestDataList>(reqLists_);
        bitField0_ |= 0x00002000;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilder<
        com.gbft.framework.data.RequestDataList, com.gbft.framework.data.RequestDataList.Builder, com.gbft.framework.data.RequestDataListOrBuilder> reqListsBuilder_;

    /**
     * <code>repeated .RequestDataList reqLists = 14;</code>
     */
    public java.util.List<com.gbft.framework.data.RequestDataList> getReqListsList() {
      if (reqListsBuilder_ == null) {
        return java.util.Collections.unmodifiableList(reqLists_);
      } else {
        return reqListsBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .RequestDataList reqLists = 14;</code>
     */
    public int getReqListsCount() {
      if (reqListsBuilder_ == null) {
        return reqLists_.size();
      } else {
        return reqListsBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .RequestDataList reqLists = 14;</code>
     */
    public com.gbft.framework.data.RequestDataList getReqLists(int index) {
      if (reqListsBuilder_ == null) {
        return reqLists_.get(index);
      } else {
        return reqListsBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .RequestDataList reqLists = 14;</code>
     */
    public Builder setReqLists(
        int index, com.gbft.framework.data.RequestDataList value) {
      if (reqListsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureReqListsIsMutable();
        reqLists_.set(index, value);
        onChanged();
      } else {
        reqListsBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .RequestDataList reqLists = 14;</code>
     */
    public Builder setReqLists(
        int index, com.gbft.framework.data.RequestDataList.Builder builderForValue) {
      if (reqListsBuilder_ == null) {
        ensureReqListsIsMutable();
        reqLists_.set(index, builderForValue.build());
        onChanged();
      } else {
        reqListsBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .RequestDataList reqLists = 14;</code>
     */
    public Builder addReqLists(com.gbft.framework.data.RequestDataList value) {
      if (reqListsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureReqListsIsMutable();
        reqLists_.add(value);
        onChanged();
      } else {
        reqListsBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .RequestDataList reqLists = 14;</code>
     */
    public Builder addReqLists(
        int index, com.gbft.framework.data.RequestDataList value) {
      if (reqListsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureReqListsIsMutable();
        reqLists_.add(index, value);
        onChanged();
      } else {
        reqListsBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .RequestDataList reqLists = 14;</code>
     */
    public Builder addReqLists(
        com.gbft.framework.data.RequestDataList.Builder builderForValue) {
      if (reqListsBuilder_ == null) {
        ensureReqListsIsMutable();
        reqLists_.add(builderForValue.build());
        onChanged();
      } else {
        reqListsBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .RequestDataList reqLists = 14;</code>
     */
    public Builder addReqLists(
        int index, com.gbft.framework.data.RequestDataList.Builder builderForValue) {
      if (reqListsBuilder_ == null) {
        ensureReqListsIsMutable();
        reqLists_.add(index, builderForValue.build());
        onChanged();
      } else {
        reqListsBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .RequestDataList reqLists = 14;</code>
     */
    public Builder addAllReqLists(
        java.lang.Iterable<? extends com.gbft.framework.data.RequestDataList> values) {
      if (reqListsBuilder_ == null) {
        ensureReqListsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, reqLists_);
        onChanged();
      } else {
        reqListsBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .RequestDataList reqLists = 14;</code>
     */
    public Builder clearReqLists() {
      if (reqListsBuilder_ == null) {
        reqLists_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00002000);
        onChanged();
      } else {
        reqListsBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .RequestDataList reqLists = 14;</code>
     */
    public Builder removeReqLists(int index) {
      if (reqListsBuilder_ == null) {
        ensureReqListsIsMutable();
        reqLists_.remove(index);
        onChanged();
      } else {
        reqListsBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .RequestDataList reqLists = 14;</code>
     */
    public com.gbft.framework.data.RequestDataList.Builder getReqListsBuilder(
        int index) {
      return getReqListsFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .RequestDataList reqLists = 14;</code>
     */
    public com.gbft.framework.data.RequestDataListOrBuilder getReqListsOrBuilder(
        int index) {
      if (reqListsBuilder_ == null) {
        return reqLists_.get(index);  } else {
        return reqListsBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .RequestDataList reqLists = 14;</code>
     */
    public java.util.List<? extends com.gbft.framework.data.RequestDataListOrBuilder> 
         getReqListsOrBuilderList() {
      if (reqListsBuilder_ != null) {
        return reqListsBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(reqLists_);
      }
    }
    /**
     * <code>repeated .RequestDataList reqLists = 14;</code>
     */
    public com.gbft.framework.data.RequestDataList.Builder addReqListsBuilder() {
      return getReqListsFieldBuilder().addBuilder(
          com.gbft.framework.data.RequestDataList.getDefaultInstance());
    }
    /**
     * <code>repeated .RequestDataList reqLists = 14;</code>
     */
    public com.gbft.framework.data.RequestDataList.Builder addReqListsBuilder(
        int index) {
      return getReqListsFieldBuilder().addBuilder(
          index, com.gbft.framework.data.RequestDataList.getDefaultInstance());
    }
    /**
     * <code>repeated .RequestDataList reqLists = 14;</code>
     */
    public java.util.List<com.gbft.framework.data.RequestDataList.Builder> 
         getReqListsBuilderList() {
      return getReqListsFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilder<
        com.gbft.framework.data.RequestDataList, com.gbft.framework.data.RequestDataList.Builder, com.gbft.framework.data.RequestDataListOrBuilder> 
        getReqListsFieldBuilder() {
      if (reqListsBuilder_ == null) {
        reqListsBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
            com.gbft.framework.data.RequestDataList, com.gbft.framework.data.RequestDataList.Builder, com.gbft.framework.data.RequestDataListOrBuilder>(
                reqLists_,
                ((bitField0_ & 0x00002000) != 0),
                getParentForChildren(),
                isClean());
        reqLists_ = null;
      }
      return reqListsBuilder_;
    }

    // @@protoc_insertion_point(builder_scope:RequestData)
  }

  // @@protoc_insertion_point(class_scope:RequestData)
  private static final com.gbft.framework.data.RequestData DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.gbft.framework.data.RequestData();
  }

  public static com.gbft.framework.data.RequestData getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<RequestData>
      PARSER = new com.google.protobuf.AbstractParser<RequestData>() {
    @java.lang.Override
    public RequestData parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<RequestData> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<RequestData> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.gbft.framework.data.RequestData getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

